### PR TITLE
Support Epic's "Easy Anti Cheat"

### PR DESCRIPTION
**Pull request by kristjanvalur**
See issue #975

Two changes are made, for the Windows platform:

- The target process is opened with _limited_ permissions, and only upgraded to full permission when required.  When an anti-cheat watchdog is present, the target process is often protected until it crashes.
- The target thread may be already suspended by the watchdog process.  Accept a failure to suspend the target thread.

### CODE REVIEW

**Comment by bitsandfoxes** [comment]
Thanks for contributing!

**Review by Swatinem — APPROVED** [review]

**Comment by supervacuus** [comment]
I also tested this with the WER module and saw no regressions. Thanks!

**Review by supervacuus — APPROVED** [review]

**Comment by p0358** [comment]
> If your crash dumper also meets the requirements, then setting the executable’s file name to anything that begins with “CrashReport” will allow it to operate in the same way.

So there was no need to do that step to get it working? (from EAC's dev docs) Or perhaps it also recognizes `crashpad_handler.exe` as supported name? I'm considering implementing EAC at some point, so I'm a bit curious about that...

**Comment by supervacuus** [comment]
> So there was no need to do that step to get it working?

I did not read it this way. To me, it reads like you need the changes in this PR _and_ must change the name of the executable. However, you can provide the actual name of the `crashpad_handler` via options in the Native SDK.
 
Maybe @kristjanvalur can chime in.

**Comment by kristjanvalur** [comment]
Im not sure what it means for EAC to know the name of your crash dumper.
In our experience, even declaring that to eac didn't help.
It was on advice from epic that the crash reporter should only request limited access to the process regardless, and then upgrade it on demand. Requesting full access on startup would fail.

**Comment by supervacuus** [comment]
Thanks, @kristjanvalur. I think the question is whether the code changes in `crashpad` are enough or if a name change of the `crashpad_handler` is _also_ required. Did you do both, or did the changes to the code suffice?

**Comment by kristjanvalur** [comment]
We didn't do change the name, but we did mention the correct name in the
EAC config file. I think that if the process isn't listed as a crash
handling process, either by name change or by providing it's name in
config, it won't even get permission to open a limited process handle to
the parent process.  I guess both requirements need to be met.

**Pull request merged**
